# Generated by Django 5.1.5 on 2025-01-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_friendship_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
